In [ ]:
# 판다스 로드 
import pandas as pd

In [ ]:
# os 모듈 로드 
import os

In [ ]:
# 해당하는 경로에 있는 파일들의 리스트 
# 폴더 경로는 상위폴더(../)로 이동->csv라는 하위폴더(/csv/)로 이동->2017하위폴더(/2017/)로 이동
file_list = os.listdir("../csv/2017/")
print(file_list)

In [ ]:
# 파일의 리스트를 가지고 반복문 사용
# 각각의 파일들을 pandas를 이용하여 데이터프레임으로 변환
# 데이터프레임 결합 (concat을 이용하여 단순한 행을 결합)

In [ ]:
# for문 사용 
# case1
for i in range(0, len(file_list), 1):
    print(file_list[i])
# case2
for i in file_list:
    print(i)

In [ ]:
#해당하는 csv파일을 데이터프레임으로 로드하려면 어떤 함수는? 
# read_csv(해당하는 파일의 경로)
pd.read_csv("../csv/2017/"+file_list[0])

In [ ]:
# concat 함수를 사용 
# pd.concat([df, df2, df3, ....], axis=(0,1) , ignore_index=bool)

# 비어있는 데이터프레임 하나 생성 
df = pd.DataFrame()

# 반복문을 이용하여 파일들을 로드하여 비어있는 데이터프레임에 결합
for i in range(0, len(file_list), 1):
    path = "../csv/2017/"
    data = pd.read_csv(path + file_list[i])

    # df와 data를 결합
    df = pd.concat([df, data], axis=0, ignore_index=True)

df.info()

In [ ]:
# 2018년도 데이터를 확인 

file_path = "../csv/2018/"
file_list = os.listdir(file_path)
# 비어있는 데이터프레임을 생성
df = pd.DataFrame()
for file in file_list:
    print(file_path + file)
    data = pd.read_csv(file_path + file)
    # 데이터프레임 결합
    df = pd.concat([df, data], axis=0, ignore_index=True)
df.info()

In [ ]:
file_path = "../csv/2019/"
file_list = os.listdir(file_path)
# 비어있는 데이터프레임을 생성
df = pd.DataFrame()
for file in file_list:
    # print(file_path + file)
    data = pd.read_json(file_path + file)
    # 데이터프레임 결합
    df = pd.concat([df, data], axis=0, ignore_index=True)
df.info()

In [ ]:
!pip install openpyxl

In [19]:
file_path = "../csv/2020/"
file_list = os.listdir(file_path)
# 비어있는 데이터프레임을 생성
df = pd.DataFrame()
for file in file_list:
    # print(file_path + file)
    data = pd.read_excel(file_path + file)
    # 데이터프레임 결합
    df = pd.concat([df, data], axis=0, ignore_index=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70862 entries, 0 to 70861
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                70862 non-null  int64
 1   title              70862 non-null  object
 2   url                70862 non-null  object
 3   dept_nm_lvl_1      70862 non-null  object
 4   dept_nm_lvl_2      70862 non-null  object
 5   dept_nm_lvl_3      55593 non-null  object
 6   dept_nm_lvl_4      18992 non-null  object
 7   dept_nm_lvl_5      1601 non-null   object
 8   exec_yr            70862 non-null  int64
 9   exec_month         70862 non-null  int64
 10  expense_budget     1823 non-null   float64
 11  expense_execution  1338 non-null   float64
 12  category           2123 non-null   object
 13  dept_nm_full       70862 non-null  object
 14  exec_dt            70862 non-null  object
 15  exec_loc           70278 non-null  object
 16  exec_purpose       70862 non-null  object
 17  target_nm          70488 non-null  object
 18  payment_method     70862 non-null  object
 19  exec_amount        70862 non-null  int64
 20  bimok              283 non-null    object
dtypes: float64(2), int64(4), object(15)
memory usage: 11.4+ MB

In [20]:
# 2021년도 파일 리스트 
file_path = "../csv/2021/"
file_list = os.listdir(file_path)

print(file_list)

['202101_expense_list.csv', '202101_expense_list.json', '202101_expense_list.xlsx', '202101_expense_list.xml', '202102_expense_list.csv', '202102_expense_list.json', '202102_expense_list.xlsx', '202102_expense_list.xml', '202103_expense_list.csv', '202103_expense_list.json', '202103_expense_list.xlsx', '202103_expense_list.xml', '202104_expense_list.csv', '202104_expense_list.json', '202104_expense_list.xlsx', '202104_expense_list.xml', '202105_expense_list.csv', '202105_expense_list.json', '202105_expense_list.xlsx', '202105_expense_list.xml', '202106_expense_list.csv', '202106_expense_list.json', '202106_expense_list.xlsx', '202106_expense_list.xml', '202107_expense_list.csv', '202107_expense_list.json', '202107_expense_list.xlsx', '202107_expense_list.xml', '202108_expense_list.csv', '202108_expense_list.json', '202108_expense_list.xlsx', '202108_expense_list.xml', '202109_expense_list.csv', '202109_expense_list.json', '202109_expense_list.xlsx', '202109_expense_list.xml', '202110_expense_list.csv', '202110_expense_list.json', '202110_expense_list.xlsx', '202110_expense_list.xml', '202111_expense_list.csv', '202111_expense_list.json', '202111_expense_list.xlsx', '202111_expense_list.xml', '202112_expense_list.csv', '202112_expense_list.json', '202112_expense_list.xlsx', '202112_expense_list.xml']

In [33]:
file_list[3].split(".")[-1]

'xml'

In [38]:
_list = []

for file in file_list:
    if (file.split('.')[-1] == 'xlsx'):
        # print(file)
        _list.append(file)

print(_list)

['202101_expense_list.xlsx', '202102_expense_list.xlsx', '202103_expense_list.xlsx', '202104_expense_list.xlsx', '202105_expense_list.xlsx', '202106_expense_list.xlsx', '202107_expense_list.xlsx', '202108_expense_list.xlsx', '202109_expense_list.xlsx', '202110_expense_list.xlsx', '202111_expense_list.xlsx', '202112_expense_list.xlsx']

In [44]:
# 함수 생성 

def list_df(path, end_string):
    # file의 list를 변수로 생성
    file_list = os.listdir(path)
    # 확장자가 end_string과 같은 경우의 리스트만 추출
    file_list2 = []
    # 반복문을 이용하여 end_string과 같은 확장자만 파일만 file_list2에 추가
    for file in file_list:
        if (file.split(".")[-1] == end_string):
            file_list2.append(file)
    
    # file_list2가 완성이 되면 
    # file_list2를 이용하여 데이터프레임을 결합

    # 비어있는 데이터프레임을 생성 
    result = pd.DataFrame()

    # for문을 이용하여 file_list2 파일들을 비어있는 데이터프레임에 결합
    for file in file_list2:
        print(path + file)
        if(end_string == 'csv'):
            data = pd.read_csv(path + file)
        elif (end_string == 'json'):
            data = pd.read_json(path + file)
        elif (end_string == 'xlsx') | (end_string == 'xls'):
            data = pd.read_excel(path + file)
        
        # result와 data 라는 2개의 데이터프레임을 유니언 결합
        result = pd.concat([result, data], axis=0, ignore_index=True)
    
    return result

In [46]:
list_df('../csv/2021/', 'xlsx')

../csv/2021/202101_expense_list.xlsx
../csv/2021/202102_expense_list.xlsx
../csv/2021/202103_expense_list.xlsx
../csv/2021/202104_expense_list.xlsx
../csv/2021/202105_expense_list.xlsx
../csv/2021/202106_expense_list.xlsx
../csv/2021/202107_expense_list.xlsx
../csv/2021/202108_expense_list.xlsx
../csv/2021/202109_expense_list.xlsx
../csv/2021/202110_expense_list.xlsx
../csv/2021/202111_expense_list.xlsx
../csv/2021/202112_expense_list.xlsx

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,...,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount,bimok
0,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 관리과,2021-01-25 00:00,NaN,소속직원 경조사비,"김광옥, 김용성",현금,100000,NaN
1,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 운영과,2021-01-22 00:00,복시루,운영과 다과구매-전출직원선물,NaN,카드,90000,NaN
2,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 시설보수과,2021-01-21 00:00,떡시루,소속직원 송별떡,시설보수과장외 27명,카드,80000,NaN
3,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 운영과,2021-01-21 00:00,서울시청매점,운영과 다과구매-전출직원선물,NaN,제로페이,48000,NaN
4,22249566,2021년 1월 사업소 물재생센터 중랑물재생센터 업무추진비 - 전체,http://opengov.seoul.go.kr/public/22249566,사업소,물재생센터,중랑물재생센터,NaN,NaN,2021,1,...,NaN,NaN,중랑물재생센터 운영과,2021-01-21 00:00,복시루,운영과 다과구매-전출직원선물,NaN,카드,75000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83814,25116134,2021년 12월 사업소 상수도사업본부 뚝도아리수정수센터 업무추진비 - 기관운영 시...,http://opengov.seoul.go.kr/expense/25116134,사업소,상수도사업본부,뚝도아리수정수센터,NaN,NaN,2021,12,...,0.0,NaN,뚝도아리수 정수센터,2021-12-21 19:44,고기사람(서대문구 충정로4길 26),사업소간 교차점검 결과보고 간담회,소장 외 2명,카드,97000,NaN
83815,25116134,2021년 12월 사업소 상수도사업본부 뚝도아리수정수센터 업무추진비 - 기관운영 시...,http://opengov.seoul.go.kr/expense/25116134,사업소,상수도사업본부,뚝도아리수정수센터,NaN,NaN,2021,12,...,0.0,NaN,뚝도아리수 정수센터,2021-12-07 11:57,장수숯불갈비(성동구 성덕정길40),신임소장과 전직원 순회 소통 (D팀) 간담회,소장 외 5명,카드,120000,NaN
83816,25116134,2021년 12월 사업소 상수도사업본부 뚝도아리수정수센터 업무추진비 - 기관운영 시...,http://opengov.seoul.go.kr/expense/25116134,사업소,상수도사업본부,뚝도아리수정수센터,NaN,NaN,2021,12,...,0.0,NaN,뚝도아리수 정수센터,2021-12-02 12:07,장수숯불갈비(성동구 성덕정길39),신임소장과 전직원 순회 소통 (C팀) 간담회,소장 외 7명,카드,116000,NaN
83817,25116134,2021년 12월 사업소 상수도사업본부 뚝도아리수정수센터 업무추진비 - 기관운영 시...,http://opengov.seoul.go.kr/expense/25116134,사업소,상수도사업본부,뚝도아리수정수센터,NaN,NaN,2021,12,...,0.0,NaN,뚝도아리수 정수센터,2021-12-28 16:48,현대마트(성동구 성덕정길29),기관운영 물품 구매,소장,카드,113180,NaN
83818,25116134,2021년 12월 사업소 상수도사업본부 뚝도아리수정수센터 업무추진비 - 기관운영 시...,http://opengov.seoul.go.kr/expense/25116134,사업소,상수도사업본부,뚝도아리수정수센터,NaN,NaN,2021,12,...,0.0,NaN,뚝도아리수 정수센터,2021-12-28 10:15,서울시청매점(중구 덕수궁길),소장실 운영물품 구매,소장,카드,84000,NaN